### ISSUE TITLE
[Documentação] - Valor do Bilhete

### ISSUE THREAD

**Issue by JuanLiraEst** [CallmeHenrique/Atv7TicketMachine#11]
Resumo: Não foi especificado o valor do bilhete que deve ser debitado do saldo.
Arquivo: Especificação - TicketMachine.pdf
Criticidade: Alto
Categoria do Defeito: Defeito de Requisitos - Omissão

**Comment by CallmeHenrique** [comment]
Como o valor do bilhete não foi informado na EF, não podemos adicionar uma informação que não temos, portanto deixaremos esse ponto em aberto na EF.
