### ISSUE TITLE
[Bug] - Retorno incorreto da função

### ISSUE THREAD

**Issue by CallmeHenrique** [CallmeHenrique/Atv7TicketMachine#19]
Resumo: A função getTroco retorna um iterator, porém a variável this.saldo, que está sendo retornada, é do tipo Int
Arquivo: TicketMachine.java
Criticidade: Alto
Categoria do Defeito: Defeito de Código - Computação

**Comment by JuanLiraEst** [comment]
Corrigido via PR #20
