### ISSUE TITLE
[Bug] - Exception sem implementação

### ISSUE THREAD

**Issue by CallmeHenrique** [CallmeHenrique/Atv7TicketMachine#7]
Resumo: Não tem sentido criar uma implementação de uma exceção, sendo que nada foi criado nessa implementação, poderia ter sido utilizado um "throws Exception" diretamente no local onde foi colocado a implementação dessa exceção.
Arquivo: SaldoInsuficienteException.java
Criticidade: Baixo
Categoria do Defeito: Defeito de Código - Excesso

**Comment by JuanLiraEst** [comment]
Após uma reavaliação, a criação dessa exception se faz necessária uma vez que devemos especificar o tipo de erro que ocorre no código, utilizar Exception deixaria a mensagem de erro genérica.
Utilizar classes de exception também facilita futura manutenções específicas para esse erro.
